{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secrets"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
---
{{- end }}
{{- if .Values.hfToken }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-hf-token"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  token: {{ .Values.hfToken | b64enc | quote }}
{{- end }}
